import { authOptions } from "@/auth";
import { getInstantAdminDb } from "@/lib/db/instant-admin";
import { listLibraryBooksForUser } from "@/lib/server/library-books";
import { getAppUserByEmail } from "@/lib/server/get-app-user";
import { getServerSession } from "next-auth";
import Link from "next/link";
import { RemoveUserBookButton } from "@/components/profile/remove-user-book-button";
import Image from "next/image";
import asset2 from "@/ASSETS/Asset 2.webp";

export default async function ProfilePage() {
  const session = await getServerSession(authOptions);
  const email = session?.user?.email;
  const appUser = email ? await getAppUserByEmail(email) : null;

  if (!appUser) {
    return (
      <main>
        <h1 className="font-serif text-3xl leading-tight md:text-4xl">Profile</h1>
        <p className="mt-4 max-w-xl text-base text-[var(--text-secondary)]">
          Sign in to see your saved books.
        </p>
      </main>
    );
  }

  const libraryBooks = await listLibraryBooksForUser(appUser.id);
  // `is_past_book` is not a reliable indicator for "Finished" anymore:
  // when a currently-tracked book is marked as finished, we keep logs/
  // reflections for stats and set `is_past_book: false`.
  // So we use the `status` field primarily.
  const finished = libraryBooks.filter((b) => b.status === "finished" || b.isPastBook);
  const wantToRead = libraryBooks.filter((b) => b.status === "want_to_read");
  const currentlyReading = libraryBooks.filter((b) => b.status === "currently_reading");

  const db = getInstantAdminDb();
  const explanationByGoogleId = new Map<string, string>();

  const coerceTasteSummary = (value: unknown): string | null => {
    if (value == null) return null;
    if (typeof value === "string") {
      const t = value.trim();
      return t.length ? t : null;
    }
    const s = String(value).trim();
    return s.length ? s : null;
  };

  const coerceDateLabel = (value: unknown): string | null => {
    if (value == null) return null;
    if (value instanceof Date) {
      if (Number.isNaN(value.getTime())) return null;
      return value.toISOString();
    }
    if (typeof value === "string") {
      const s = value.trim();
      if (!s) return null;
      return s;
    }
    const s = String(value).trim();
    return s.length ? s : null;
  };

  // Taste profile is generated by the recommendations flow and stored on the user.
  // `getAppUserByEmail` already fetched the `users` row, so prefer reading from it first
  // (it avoids cases where the follow-up `id` query doesn't return the field).
  const fromAppUser = coerceTasteSummary((appUser as any).taste_profile_summary);
  const fromAppUserUpdatedAt = coerceDateLabel((appUser as any).taste_profile_updated_at);

  let hydratedTasteProfileSummary = fromAppUser;
  let hydratedTasteProfileUpdatedAtLabel = fromAppUserUpdatedAt;
  if (!hydratedTasteProfileSummary) {
    const tasteRes = await (db as any).query({
      users: {
        $: { where: { id: appUser.id } },
      },
    } as any);
    const tasteRow = Array.isArray(tasteRes.users) ? tasteRes.users[0] : null;
    hydratedTasteProfileSummary = tasteRow ? coerceTasteSummary((tasteRow as any).taste_profile_summary) : null;
    if (!hydratedTasteProfileUpdatedAtLabel) {
      hydratedTasteProfileUpdatedAtLabel = tasteRow ? coerceDateLabel((tasteRow as any).taste_profile_updated_at) : null;
    }
  }

  // Fallback: sometimes the taste profile is persisted alongside the recommendations record.
  // Prefer the latest ai_recommendations with a non-empty taste_profile_summary.
  if (!hydratedTasteProfileSummary) {
    const aiTasteRes = await (db as any).query({
      ai_recommendations: {
        $: { where: { owner_user_id: appUser.id } },
      },
    } as any);

    const rows = Array.isArray(aiTasteRes.ai_recommendations) ? aiTasteRes.ai_recommendations : [];
    let bestSummary: string | null = null;
    let bestTimeMs = -1;
    let bestUpdatedAtLabel: string | null = null;

    for (const row of rows) {
      const r = row as any;
      const summary = coerceTasteSummary(r?.taste_profile_summary);
      if (!summary) continue;

      const dtRaw = r?.generated_at ?? r?.created_at;
      const d = dtRaw instanceof Date ? dtRaw : dtRaw ? new Date(String(dtRaw)) : null;
      const timeMs = d && !Number.isNaN(d.getTime()) ? d.getTime() : 0;
      if (timeMs > bestTimeMs) {
        bestTimeMs = timeMs;
        bestSummary = summary;
        bestUpdatedAtLabel = d && !Number.isNaN(d.getTime()) ? d.toISOString() : null;
      }
    }

    hydratedTasteProfileSummary = bestSummary;
    hydratedTasteProfileUpdatedAtLabel = hydratedTasteProfileUpdatedAtLabel ?? bestUpdatedAtLabel;
  }

  await Promise.all(
    libraryBooks.map(async (b) => {
      if (!b.googleBooksId) return;
      const res = await (db as any).query({
        ai_recommendation_items: {
          $: { where: { owner_user_id: appUser.id, google_books_id: b.googleBooksId } },
        },
      } as any);

      const row = Array.isArray(res.ai_recommendation_items)
        ? (res.ai_recommendation_items[0] as any)
        : null;
      if (row && typeof row.explanation === "string") {
        explanationByGoogleId.set(b.googleBooksId, row.explanation);
      }
    }),
  );

  return (
    <main className="flex flex-col gap-10">
      <section className="rounded-xl border border-[var(--border-subtle)] bg-[var(--surface)] p-8 md:p-12">
        <p className="text-sm text-[var(--text-secondary)]">Profile</p>
        <div className="mt-3 flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
          <div className="min-w-0 md:max-w-[50%]">
            <h1 className="font-serif text-4xl leading-tight tracking-tight md:text-5xl">
              Your shelves
            </h1>
            <p className="mt-4 break-words text-base text-[var(--text-secondary)]">
              Books you saved from recommendations will show the reason they matched your taste.
            </p>
          </div>
          <div className="flex justify-end md:flex-shrink-0">
            <Image
              src={asset2}
              alt=""
              className="h-56 w-auto object-contain md:h-72"
              priority
            />
          </div>
        </div>

        <div className="mt-8 rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-subtle)] p-5">
          <h2 className="font-serif text-2xl leading-tight">Your taste profile</h2>
          {hydratedTasteProfileSummary ? (
            <p className="mt-3 whitespace-pre-wrap text-base text-[var(--text-secondary)]">
              {hydratedTasteProfileSummary}
            </p>
          ) : (
            <p className="mt-3 whitespace-pre-wrap text-base text-[var(--text-secondary)]">
              Taste profile text is not available yet. Try generating recommendations again.
            </p>
          )}
          {hydratedTasteProfileUpdatedAtLabel ? (
            <p className="mt-2 text-xs text-[var(--text-secondary)]">Updated: {hydratedTasteProfileUpdatedAtLabel}</p>
          ) : null}
        </div>
      </section>

      <section className="rounded-xl border border-[var(--border-subtle)] bg-[var(--surface)] p-6 md:p-8">
        <div className="flex items-end justify-between gap-4">
          <h2 className="font-serif text-2xl leading-tight">Want to Read</h2>
          <p className="text-sm text-[var(--text-secondary)]">{wantToRead.length} saved</p>
        </div>

        {wantToRead.length === 0 ? (
          <p className="mt-4 text-sm text-[var(--text-secondary)]">No books here yet.</p>
        ) : (
          <ul className="mt-5 grid gap-3 sm:grid-cols-2">
            {wantToRead.map((b) => (
              <li key={b.userBookId}>
                <div className="flex items-start justify-between gap-3 rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-subtle)] p-3 transition-colors hover:border-[var(--brand-blue)]">
                  <Link
                    href={`/book/${b.userBookId}`}
                    className="flex flex-1 flex-col gap-2 min-w-0"
                  >
                    <div className="flex items-center gap-3">
                      {b.thumbnailUrl ? (
                        // eslint-disable-next-line @next/next/no-img-element
                        <img
                          src={b.thumbnailUrl}
                          alt=""
                          className="h-14 w-10 shrink-0 rounded object-cover"
                        />
                      ) : (
                        <div className="flex h-14 w-10 shrink-0 items-center justify-center rounded bg-[var(--surface)] text-[10px] text-[var(--text-secondary)]">
                          —
                        </div>
                      )}
                      <div className="min-w-0">
                        <p className="truncate text-sm font-medium text-[var(--text-primary)]">{b.title}</p>
                        {b.googleBooksId && explanationByGoogleId.has(b.googleBooksId) ? (
                          <p className="mt-1 line-clamp-3 text-xs text-[var(--text-secondary)]">
                            Recommended because: {explanationByGoogleId.get(b.googleBooksId)}
                          </p>
                        ) : null}
                      </div>
                    </div>
                  </Link>

                  <RemoveUserBookButton userBookId={b.userBookId} />
                </div>
              </li>
            ))}
          </ul>
        )}
      </section>

      <section className="rounded-xl border border-[var(--border-subtle)] bg-[var(--surface)] p-6 md:p-8">
        <div className="flex items-end justify-between gap-4">
          <h2 className="font-serif text-2xl leading-tight">Currently Reading</h2>
          <p className="text-sm text-[var(--text-secondary)]">{currentlyReading.length} active</p>
        </div>

        {currentlyReading.length === 0 ? (
          <p className="mt-4 text-sm text-[var(--text-secondary)]">No active books yet.</p>
        ) : (
          <ul className="mt-5 grid gap-3 sm:grid-cols-2">
            {currentlyReading.map((b) => (
              <li key={b.userBookId}>
                <div className="flex items-start justify-between gap-3 rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-subtle)] p-3 transition-colors hover:border-[var(--brand-blue)]">
                  <Link
                    href={`/book/${b.userBookId}`}
                    className="flex flex-1 flex-col gap-2 min-w-0"
                  >
                    <div className="flex items-center gap-3">
                      {b.thumbnailUrl ? (
                        // eslint-disable-next-line @next/next/no-img-element
                        <img
                          src={b.thumbnailUrl}
                          alt=""
                          className="h-14 w-10 shrink-0 rounded object-cover"
                        />
                      ) : (
                        <div className="flex h-14 w-10 shrink-0 items-center justify-center rounded bg-[var(--surface)] text-[10px] text-[var(--text-secondary)]">
                          —
                        </div>
                      )}
                      <div className="min-w-0">
                        <p className="truncate text-sm font-medium text-[var(--text-primary)]">{b.title}</p>
                        {b.googleBooksId && explanationByGoogleId.has(b.googleBooksId) ? (
                          <p className="mt-1 line-clamp-3 text-xs text-[var(--text-secondary)]">
                            Recommended because: {explanationByGoogleId.get(b.googleBooksId)}
                          </p>
                        ) : null}
                      </div>
                    </div>
                  </Link>

                  <RemoveUserBookButton userBookId={b.userBookId} />
                </div>
              </li>
            ))}
          </ul>
        )}
      </section>

      <section className="rounded-xl border border-[var(--border-subtle)] bg-[var(--surface)] p-6 md:p-8">
        <div className="flex items-end justify-between gap-4">
          <h2 className="font-serif text-2xl leading-tight">Finished</h2>
          <p className="text-sm text-[var(--text-secondary)]">{finished.length} total</p>
        </div>

        {finished.length === 0 ? (
          <p className="mt-4 text-sm text-[var(--text-secondary)]">No finished books yet.</p>
        ) : (
          <ul className="mt-5 grid gap-3 sm:grid-cols-2">
            {finished.map((b) => (
              <li key={b.userBookId}>
                <Link
                  href={`/book/${b.userBookId}`}
                  className="flex flex-col gap-2 rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-subtle)] p-3 transition-colors hover:border-[var(--brand-blue)]"
                >
                  <div className="flex items-center gap-3">
                    {b.thumbnailUrl ? (
                      // eslint-disable-next-line @next/next/no-img-element
                      <img
                        src={b.thumbnailUrl}
                        alt=""
                        className="h-14 w-10 shrink-0 rounded object-cover"
                      />
                    ) : (
                      <div className="flex h-14 w-10 shrink-0 items-center justify-center rounded bg-[var(--surface)] text-[10px] text-[var(--text-secondary)]">
                        —
                      </div>
                    )}
                    <div className="min-w-0">
                      <p className="truncate text-sm font-medium text-[var(--text-primary)]">{b.title}</p>
                      {b.googleBooksId && explanationByGoogleId.has(b.googleBooksId) ? (
                        <p className="mt-1 line-clamp-3 text-xs text-[var(--text-secondary)]">
                          Recommended because: {explanationByGoogleId.get(b.googleBooksId)}
                        </p>
                      ) : null}
                    </div>
                  </div>
                </Link>
              </li>
            ))}
          </ul>
        )}
      </section>
    </main>
  );
}
